vim.opt.tabstop=4
vim.opt.softtabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab=true
vim.opt.guifont='Maple Mono NF:h12'
vim.opt.nu=true
vim.opt.relativenumber = true
vim.opt.smartindent = true
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = vim.fn.stdpath("cache") .. "/undodir"
vim.opt.undofile = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.termguicolors=true
vim.opt.scrolloff=8
vim.opt.updatetime=50
vim.opt.colorcolumn = "80,120"
vim.opt.signcolumn = 'yes'
vim.opt.showmode = false
