#!/bin/env zsh

function ls {
    if command -v eza &>/dev/null; then
        command eza --icons --group-directories-first $argv
    elif command -v exa &>/dev/null; then
        command exa --icons --group-directories-first $argv
    else
        command ls --group-directories-first $argv
    fi
}
